const TOMATO_TIMER_STARTED = 'tomato/TOMATO_TIMER_STARTED';
const TOMATO_TIMER_STOPPED = 'tomato/TOMATO_TIMER_STOPPED';
const TOMATO_CURRENT_TIME_SET = 'tomato/TOMATO_CURRENT_TIME_SET';
const TOMATO_TIME_RESET = 'tomato/TOMATO_TIME_RESET';
const NEXT_ROUND_SET = 'tomato/NEXT_ROUND_SET';
const NEXT_SESSION_SET = 'tomato/NEXT_SESSION_SET';
const ROUND_TIME_EXPIRED = 'tomato/ROUND_TIME_EXPIRED';

export default {
  TOMATO_TIMER_STARTED,
  TOMATO_TIMER_STOPPED,
  TOMATO_CURRENT_TIME_SET,
  TOMATO_TIME_RESET,
  NEXT_ROUND_SET,
  NEXT_SESSION_SET,
  ROUND_TIME_EXPIRED
}